# Generated by Django 2.1.4 on 2018-12-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
