# Generated by Django 2.1.4 on 2019-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_tempfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempfiles',
            name='file',
            field=models.FileField(upload_to='temp'),
        ),
    ]
