# Generated by Django 2.1.4 on 2019-01-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_auto_20190111_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempFiles',
        ),
    ]
