# Generated by Django 2.1.4 on 2019-01-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_delete_tempfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainedmodels',
            old_name='description',
            new_name='modelDescription',
        ),
        migrations.RenameField(
            model_name='trainedmodels',
            old_name='title',
            new_name='modelTitle',
        ),
    ]
